/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSplatRouteImport } from './routes/admin/$'
import { Route as AdminAppointmentsRouteImport } from './routes/admin/appointments'
import { Route as AdminNewTokenRouteImport } from './routes/admin/new-token'
import { Route as AdminPatientsRouteImport } from './routes/admin/patients'
import { Route as AdminPrescriptionsRouteImport } from './routes/admin/prescriptions'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminTrashRouteImport } from './routes/admin/trash'
import { Route as SuperadminIndexRouteImport } from './routes/superadmin/index'
import { Route as SuperadminSplatRouteImport } from './routes/superadmin/$'
import { Route as SuperadminSubscriptionRouteImport } from './routes/superadmin/subscription'
import { Route as SuperadminWhiteLabelRouteImport } from './routes/superadmin/white-label'
import { Route as SuperadminLoginRouteImport } from './routes/superadmin_.login'
import { Route as AdminPatientsIndexRouteImport } from './routes/admin/patients.index'
import { Route as AdminPatientsPatientIdRouteImport } from './routes/admin/patients.$patientId'
import { Route as AdminPatientsNewRouteImport } from './routes/admin/patients.new'
import { Route as AdminPatientsQuickRouteImport } from './routes/admin/patients.quick'
import { Route as SuperadminSubscriptionClinicIdRouteImport } from './routes/superadmin/subscription.$clinicId'
import { Route as AdminPatientsPatientIdIndexRouteImport } from './routes/admin/patients.$patientId.index'
import { Route as AdminPatientsPatientIdEditRouteImport } from './routes/admin/patients.$patientId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewTokenRoute = AdminNewTokenRouteImport.update({
  id: '/new-token',
  path: '/new-token',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatientsRoute = AdminPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrescriptionsRoute = AdminPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrashRoute = AdminTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AdminRoute,
} as any)
const SuperadminIndexRoute = SuperadminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminSplatRoute = SuperadminSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminSubscriptionRoute = SuperadminSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminWhiteLabelRoute = SuperadminWhiteLabelRouteImport.update({
  id: '/white-label',
  path: '/white-label',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminLoginRoute = SuperadminLoginRouteImport.update({
  id: '/superadmin_/login',
  path: '/superadmin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPatientsIndexRoute = AdminPatientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPatientsRoute,
} as any)
const AdminPatientsPatientIdRoute = AdminPatientsPatientIdRouteImport.update({
  id: '/$patientId',
  path: '/$patientId',
  getParentRoute: () => AdminPatientsRoute,
} as any)
const AdminPatientsNewRoute = AdminPatientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminPatientsRoute,
} as any)
const AdminPatientsQuickRoute = AdminPatientsQuickRouteImport.update({
  id: '/quick',
  path: '/quick',
  getParentRoute: () => AdminPatientsRoute,
} as any)
const SuperadminSubscriptionClinicIdRoute =
  SuperadminSubscriptionClinicIdRouteImport.update({
    id: '/$clinicId',
    path: '/$clinicId',
    getParentRoute: () => SuperadminSubscriptionRoute,
  } as any)
const AdminPatientsPatientIdIndexRoute =
  AdminPatientsPatientIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminPatientsPatientIdRoute,
  } as any)
const AdminPatientsPatientIdEditRoute =
  AdminPatientsPatientIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AdminPatientsPatientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/new-token': typeof AdminNewTokenRoute
  '/admin/patients': typeof AdminPatientsRouteWithChildren
  '/admin/prescriptions': typeof AdminPrescriptionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/trash': typeof AdminTrashRoute
  '/superadmin/$': typeof SuperadminSplatRoute
  '/superadmin/subscription': typeof SuperadminSubscriptionRouteWithChildren
  '/superadmin/white-label': typeof SuperadminWhiteLabelRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/admin/patients/$patientId': typeof AdminPatientsPatientIdRouteWithChildren
  '/admin/patients/new': typeof AdminPatientsNewRoute
  '/admin/patients/quick': typeof AdminPatientsQuickRoute
  '/superadmin/subscription/$clinicId': typeof SuperadminSubscriptionClinicIdRoute
  '/admin/patients/': typeof AdminPatientsIndexRoute
  '/admin/patients/$patientId/edit': typeof AdminPatientsPatientIdEditRoute
  '/admin/patients/$patientId/': typeof AdminPatientsPatientIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/new-token': typeof AdminNewTokenRoute
  '/admin/prescriptions': typeof AdminPrescriptionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/trash': typeof AdminTrashRoute
  '/superadmin/$': typeof SuperadminSplatRoute
  '/superadmin/subscription': typeof SuperadminSubscriptionRouteWithChildren
  '/superadmin/white-label': typeof SuperadminWhiteLabelRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/admin': typeof AdminIndexRoute
  '/superadmin': typeof SuperadminIndexRoute
  '/admin/patients/new': typeof AdminPatientsNewRoute
  '/admin/patients/quick': typeof AdminPatientsQuickRoute
  '/superadmin/subscription/$clinicId': typeof SuperadminSubscriptionClinicIdRoute
  '/admin/patients': typeof AdminPatientsIndexRoute
  '/admin/patients/$patientId/edit': typeof AdminPatientsPatientIdEditRoute
  '/admin/patients/$patientId': typeof AdminPatientsPatientIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/new-token': typeof AdminNewTokenRoute
  '/admin/patients': typeof AdminPatientsRouteWithChildren
  '/admin/prescriptions': typeof AdminPrescriptionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/trash': typeof AdminTrashRoute
  '/superadmin/$': typeof SuperadminSplatRoute
  '/superadmin/subscription': typeof SuperadminSubscriptionRouteWithChildren
  '/superadmin/white-label': typeof SuperadminWhiteLabelRoute
  '/superadmin_/login': typeof SuperadminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/admin/patients/$patientId': typeof AdminPatientsPatientIdRouteWithChildren
  '/admin/patients/new': typeof AdminPatientsNewRoute
  '/admin/patients/quick': typeof AdminPatientsQuickRoute
  '/superadmin/subscription/$clinicId': typeof SuperadminSubscriptionClinicIdRoute
  '/admin/patients/': typeof AdminPatientsIndexRoute
  '/admin/patients/$patientId/edit': typeof AdminPatientsPatientIdEditRoute
  '/admin/patients/$patientId/': typeof AdminPatientsPatientIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/superadmin'
    | '/terms'
    | '/admin/$'
    | '/admin/appointments'
    | '/admin/new-token'
    | '/admin/patients'
    | '/admin/prescriptions'
    | '/admin/settings'
    | '/admin/trash'
    | '/superadmin/$'
    | '/superadmin/subscription'
    | '/superadmin/white-label'
    | '/superadmin/login'
    | '/admin/'
    | '/superadmin/'
    | '/admin/patients/$patientId'
    | '/admin/patients/new'
    | '/admin/patients/quick'
    | '/superadmin/subscription/$clinicId'
    | '/admin/patients/'
    | '/admin/patients/$patientId/edit'
    | '/admin/patients/$patientId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/admin/$'
    | '/admin/appointments'
    | '/admin/new-token'
    | '/admin/prescriptions'
    | '/admin/settings'
    | '/admin/trash'
    | '/superadmin/$'
    | '/superadmin/subscription'
    | '/superadmin/white-label'
    | '/superadmin/login'
    | '/admin'
    | '/superadmin'
    | '/admin/patients/new'
    | '/admin/patients/quick'
    | '/superadmin/subscription/$clinicId'
    | '/admin/patients'
    | '/admin/patients/$patientId/edit'
    | '/admin/patients/$patientId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/superadmin'
    | '/terms'
    | '/admin/$'
    | '/admin/appointments'
    | '/admin/new-token'
    | '/admin/patients'
    | '/admin/prescriptions'
    | '/admin/settings'
    | '/admin/trash'
    | '/superadmin/$'
    | '/superadmin/subscription'
    | '/superadmin/white-label'
    | '/superadmin_/login'
    | '/admin/'
    | '/superadmin/'
    | '/admin/patients/$patientId'
    | '/admin/patients/new'
    | '/admin/patients/quick'
    | '/superadmin/subscription/$clinicId'
    | '/admin/patients/'
    | '/admin/patients/$patientId/edit'
    | '/admin/patients/$patientId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  SuperadminRoute: typeof SuperadminRouteWithChildren
  TermsRoute: typeof TermsRoute
  SuperadminLoginRoute: typeof SuperadminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/new-token': {
      id: '/admin/new-token'
      path: '/new-token'
      fullPath: '/admin/new-token'
      preLoaderRoute: typeof AdminNewTokenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patients': {
      id: '/admin/patients'
      path: '/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AdminPatientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/prescriptions': {
      id: '/admin/prescriptions'
      path: '/prescriptions'
      fullPath: '/admin/prescriptions'
      preLoaderRoute: typeof AdminPrescriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/trash': {
      id: '/admin/trash'
      path: '/trash'
      fullPath: '/admin/trash'
      preLoaderRoute: typeof AdminTrashRouteImport
      parentRoute: typeof AdminRoute
    }
    '/superadmin/': {
      id: '/superadmin/'
      path: '/'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof SuperadminIndexRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/$': {
      id: '/superadmin/$'
      path: '/$'
      fullPath: '/superadmin/$'
      preLoaderRoute: typeof SuperadminSplatRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/subscription': {
      id: '/superadmin/subscription'
      path: '/subscription'
      fullPath: '/superadmin/subscription'
      preLoaderRoute: typeof SuperadminSubscriptionRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/white-label': {
      id: '/superadmin/white-label'
      path: '/white-label'
      fullPath: '/superadmin/white-label'
      preLoaderRoute: typeof SuperadminWhiteLabelRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin_/login': {
      id: '/superadmin_/login'
      path: '/superadmin/login'
      fullPath: '/superadmin/login'
      preLoaderRoute: typeof SuperadminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/patients/': {
      id: '/admin/patients/'
      path: '/'
      fullPath: '/admin/patients/'
      preLoaderRoute: typeof AdminPatientsIndexRouteImport
      parentRoute: typeof AdminPatientsRoute
    }
    '/admin/patients/$patientId': {
      id: '/admin/patients/$patientId'
      path: '/$patientId'
      fullPath: '/admin/patients/$patientId'
      preLoaderRoute: typeof AdminPatientsPatientIdRouteImport
      parentRoute: typeof AdminPatientsRoute
    }
    '/admin/patients/new': {
      id: '/admin/patients/new'
      path: '/new'
      fullPath: '/admin/patients/new'
      preLoaderRoute: typeof AdminPatientsNewRouteImport
      parentRoute: typeof AdminPatientsRoute
    }
    '/admin/patients/quick': {
      id: '/admin/patients/quick'
      path: '/quick'
      fullPath: '/admin/patients/quick'
      preLoaderRoute: typeof AdminPatientsQuickRouteImport
      parentRoute: typeof AdminPatientsRoute
    }
    '/superadmin/subscription/$clinicId': {
      id: '/superadmin/subscription/$clinicId'
      path: '/$clinicId'
      fullPath: '/superadmin/subscription/$clinicId'
      preLoaderRoute: typeof SuperadminSubscriptionClinicIdRouteImport
      parentRoute: typeof SuperadminSubscriptionRoute
    }
    '/admin/patients/$patientId/': {
      id: '/admin/patients/$patientId/'
      path: '/'
      fullPath: '/admin/patients/$patientId/'
      preLoaderRoute: typeof AdminPatientsPatientIdIndexRouteImport
      parentRoute: typeof AdminPatientsPatientIdRoute
    }
    '/admin/patients/$patientId/edit': {
      id: '/admin/patients/$patientId/edit'
      path: '/edit'
      fullPath: '/admin/patients/$patientId/edit'
      preLoaderRoute: typeof AdminPatientsPatientIdEditRouteImport
      parentRoute: typeof AdminPatientsPatientIdRoute
    }
  }
}

interface AdminPatientsPatientIdRouteChildren {
  AdminPatientsPatientIdEditRoute: typeof AdminPatientsPatientIdEditRoute
  AdminPatientsPatientIdIndexRoute: typeof AdminPatientsPatientIdIndexRoute
}

const AdminPatientsPatientIdRouteChildren: AdminPatientsPatientIdRouteChildren =
  {
    AdminPatientsPatientIdEditRoute: AdminPatientsPatientIdEditRoute,
    AdminPatientsPatientIdIndexRoute: AdminPatientsPatientIdIndexRoute,
  }

const AdminPatientsPatientIdRouteWithChildren =
  AdminPatientsPatientIdRoute._addFileChildren(
    AdminPatientsPatientIdRouteChildren,
  )

interface AdminPatientsRouteChildren {
  AdminPatientsPatientIdRoute: typeof AdminPatientsPatientIdRouteWithChildren
  AdminPatientsNewRoute: typeof AdminPatientsNewRoute
  AdminPatientsQuickRoute: typeof AdminPatientsQuickRoute
  AdminPatientsIndexRoute: typeof AdminPatientsIndexRoute
}

const AdminPatientsRouteChildren: AdminPatientsRouteChildren = {
  AdminPatientsPatientIdRoute: AdminPatientsPatientIdRouteWithChildren,
  AdminPatientsNewRoute: AdminPatientsNewRoute,
  AdminPatientsQuickRoute: AdminPatientsQuickRoute,
  AdminPatientsIndexRoute: AdminPatientsIndexRoute,
}

const AdminPatientsRouteWithChildren = AdminPatientsRoute._addFileChildren(
  AdminPatientsRouteChildren,
)

interface AdminRouteChildren {
  AdminSplatRoute: typeof AdminSplatRoute
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminNewTokenRoute: typeof AdminNewTokenRoute
  AdminPatientsRoute: typeof AdminPatientsRouteWithChildren
  AdminPrescriptionsRoute: typeof AdminPrescriptionsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTrashRoute: typeof AdminTrashRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSplatRoute: AdminSplatRoute,
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminNewTokenRoute: AdminNewTokenRoute,
  AdminPatientsRoute: AdminPatientsRouteWithChildren,
  AdminPrescriptionsRoute: AdminPrescriptionsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTrashRoute: AdminTrashRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SuperadminSubscriptionRouteChildren {
  SuperadminSubscriptionClinicIdRoute: typeof SuperadminSubscriptionClinicIdRoute
}

const SuperadminSubscriptionRouteChildren: SuperadminSubscriptionRouteChildren =
  {
    SuperadminSubscriptionClinicIdRoute: SuperadminSubscriptionClinicIdRoute,
  }

const SuperadminSubscriptionRouteWithChildren =
  SuperadminSubscriptionRoute._addFileChildren(
    SuperadminSubscriptionRouteChildren,
  )

interface SuperadminRouteChildren {
  SuperadminSplatRoute: typeof SuperadminSplatRoute
  SuperadminSubscriptionRoute: typeof SuperadminSubscriptionRouteWithChildren
  SuperadminWhiteLabelRoute: typeof SuperadminWhiteLabelRoute
  SuperadminIndexRoute: typeof SuperadminIndexRoute
}

const SuperadminRouteChildren: SuperadminRouteChildren = {
  SuperadminSplatRoute: SuperadminSplatRoute,
  SuperadminSubscriptionRoute: SuperadminSubscriptionRouteWithChildren,
  SuperadminWhiteLabelRoute: SuperadminWhiteLabelRoute,
  SuperadminIndexRoute: SuperadminIndexRoute,
}

const SuperadminRouteWithChildren = SuperadminRoute._addFileChildren(
  SuperadminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  SuperadminRoute: SuperadminRouteWithChildren,
  TermsRoute: TermsRoute,
  SuperadminLoginRoute: SuperadminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
