/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SuperadminLayoutRouteImport } from './routes/superadmin/_layout'
import { Route as SuperadminLoginRouteImport } from './routes/superadmin/login'
import { Route as SuperadminLayoutIndexRouteImport } from './routes/superadmin/_layout/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminLayoutRoute = SuperadminLayoutRouteImport.update({
  id: '/superadmin/_layout',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminLoginRoute = SuperadminLoginRouteImport.update({
  id: '/superadmin/login',
  path: '/superadmin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminLayoutIndexRoute = SuperadminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperadminLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/superadmin': typeof SuperadminLayoutRouteWithChildren
  '/superadmin/login': typeof SuperadminLoginRoute
  '/superadmin/': typeof SuperadminLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/superadmin': typeof SuperadminLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/superadmin/_layout': typeof SuperadminLayoutRouteWithChildren
  '/superadmin/login': typeof SuperadminLoginRoute
  '/superadmin/_layout/': typeof SuperadminLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/superadmin'
    | '/superadmin/login'
    | '/superadmin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/superadmin/login'
    | '/superadmin'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/superadmin/_layout'
    | '/superadmin/login'
    | '/superadmin/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  SuperadminLayoutRoute: typeof SuperadminLayoutRouteWithChildren
  SuperadminLoginRoute: typeof SuperadminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/_layout': {
      id: '/superadmin/_layout'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/login': {
      id: '/superadmin/login'
      path: '/superadmin/login'
      fullPath: '/superadmin/login'
      preLoaderRoute: typeof SuperadminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/_layout/': {
      id: '/superadmin/_layout/'
      path: '/'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof SuperadminLayoutIndexRouteImport
      parentRoute: typeof SuperadminLayoutRoute
    }
  }
}

interface SuperadminLayoutRouteChildren {
  SuperadminLayoutIndexRoute: typeof SuperadminLayoutIndexRoute
}

const SuperadminLayoutRouteChildren: SuperadminLayoutRouteChildren = {
  SuperadminLayoutIndexRoute: SuperadminLayoutIndexRoute,
}

const SuperadminLayoutRouteWithChildren =
  SuperadminLayoutRoute._addFileChildren(SuperadminLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  SuperadminLayoutRoute: SuperadminLayoutRouteWithChildren,
  SuperadminLoginRoute: SuperadminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
